variables:
- group: Databricks-dev-environment
- group: Databricks-stg-environment
- group: Databricks-prod-environment

stages:
- stage: deploy_library_to_dev
  displayName: 'Deploy to Dev'
  condition: |
      startsWith(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
  - template: ./template/test-lib-job.yml
    parameters:
      environmentName: 'DEV'
  - template: ./template/deploy-lib-job.yml
    parameters:
      environmentName: 'DEV'
      databricksDomain: '$(databricksDomain_dev)'
      databricksToken: '$(databricksToken_dev)'
      databricksClusterId: '$(databricksClusterId_dev)'
- stage: deploy_library_to_stg
  displayName: 'Deploy to Staging'
  condition: |
      startsWith(variables['Build.SourceBranch'], 'refs/heads/staging')
  jobs:
  - template: ./template/test-lib-job.yml
    parameters:
      environmentName: 'STG'
  - template: ./template/deploy-lib-job.yml
    parameters:
      environmentName: 'STG'
      databricksDomain: '$(databricksDomain_stg)'
      databricksToken: '$(databricksToken_stg)'
      databricksClusterId: '$(databricksClusterId_stg)'
- stage: deploy_library_to_prod
  displayName: 'Deploy to Prod'
  condition: |
    startsWith(variables['Build.SourceBranch'], 'refs/heads/production')
  jobs:
  - template: ./template/test-lib-job.yml
    parameters:
      environmentName: 'PROD'
  - template: ./template/deploy-lib-job.yml
    parameters:
      environmentName: 'PROD'
      databricksDomain: '$(databricksDomain_prod)'
      databricksToken: '$(databricksToken_prod)'
      databricksClusterId: '$(databricksClusterId_prod)'