trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  basePath: 'single_tech_samples/databricks/sample4_ci_cd'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(basePath)/notebook-python-lib/notebooks'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/notebooks
  displayName: 'Copy notebooks folder'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(basePath)/notebook-python-lib/tests/integration'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/tests/integration
    displayName: 'Copy tests folder'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true # Optional
    artifactName: notebooks
  displayName: 'Publish notebooks'