# Starter Nutter pipeline

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: notebook-python-lib-vg

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    pip install nutter
  displayName: 'Install Nutter'

- script: |
    nutter run /Users/ganwa@microsoft.com/test_mynotebook $CLUSTER --recursive --junit_report
  displayName: 'Execute Nutter'
  env:
      CLUSTER: $(clusterID)
      DATABRICKS_HOST: $(databricks_host)
      DATABRICKS_TOKEN: $(databricks_token)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish Nutter results'
  condition: succeededOrFailed()
