# Azure Devops pipeline to validate what resources would be provisioned
trigger:
- none

pool:
  vmImage: ubuntu-latest

resources:
stages:
- stage: IaC
  displayName: 'IaC plan (no terraform apply)'
  jobs:
  - job: YamlLint
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
      displayName: 'Use Python 3.6'

    - script: |
        python -m pip install --upgrade pip
        python -m pip install yamllint
        yamllint Infra/*.yml -d "{extends: default, rules: {document-start: disable, line-length: disable, indentation: {spaces: 2, indent-sequences: false}}}"
      displayName: 'Run yaml lint check'

  - template: infra-ado-pipeline-template.yml
    parameters:
      buildValidation: true
      IaCRepo: self
