
trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
- group: load-testing-secrets
- name: DeviceCount
  value: 10
- name: MessageCount
  value: 1000
- name: Interval
  value: 100
- name: ContainerCount
  value: 2
- name: ServiceConnection
  value: sample-dataops

steps:
# Remember to modify the script paths. It starts from the root of your project.
- task: AzureCLI@2
  displayName: 'Run IoTSimulator on ACI'
  inputs:
    azureSubscription: $(ServiceConnection)
    scriptType: pscore
    scriptPath: e2e_samples/temperature_events/loadtesting/IoTSimulator.ps1
    arguments: '-EventHubConnectionString "`"$(Ingest-conn)`"" 
    -DeviceCount $(DeviceCount) -MessageCount $(MessageCount) -Interval $(Interval) 
    -ContainerCount $(ContainerCount) -ResourceGroup $(rg-name)'

# There are some delays until the numbers are reflected in the metrics.
- powershell: |
    Start-Sleep -s 180
  displayName: 'Delay for 3 minutes'

# Remember to modify the script paths. It starts from the root of your project.
- task: AzureCLI@2
  displayName: 'Check Load Test Result'
  inputs:
    azureSubscription: $(ServiceConnection)
    scriptType: pscore
    scriptPath: e2e_samples/temperature_events/loadtesting/LoadTestCheckResult.ps1
    arguments: '-SubscriptionId $(subscription-id) -ResourceGroup $(rg-name) 
    -EvhNamespace $(Ingest-namespace) -EvhName $(Ingest-name)'
