trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ci
    source: dbx-notebook-ci


stages:
- stage: deploy_to_test
  displayName: 'Deploy notebooks'
  variables:
  - group: dbx-env-test
  - name: notebookpath
    value: /Shared/notebook-tests/dbxbuild_$(Build.BuildId)/ 
  jobs:
  - template: ../../devops/templates/jobs/deploy-notebooks-job.yml
    parameters:
      environmentName: 'TEST'
      databricksDomain: '$(databricksDomain)'
      databricksToken: '$(databricksToken)'
      databricksNotebookPath: '$(notebookpath)'
      databricksLocalNotebookPath: $(Pipeline.Workspace)/ci/notebooks
  - template: ../../devops/templates/jobs/nutter-tests-job.yml
    parameters:
      environmentName: 'TEST'
      databricksDomain: '$(databricksDomain)'
      databricksToken: '$(databricksToken)'
      databricksClusterId: '$(databricksClusterId)'
      databricksNotebookTestPath: '$(notebookpath)'