trigger: none

stages:
  - stage: deploy_to_dev
    displayName: 'Deploy to Development'
    variables:
      - group: mdwdo-dbx-release-dev
    jobs:
      - template: templates/jobs/deploy-azure-databricks-environment.yml
        parameters:
          environmentName: 'DEV'
          serviceConnection: 'mdwdo-dbx-serviceconnection-dev'
          azureSubscriptionID: $(AZURE_SUBSCRIPTION_ID)

  - stage: deploy_to_stg
    displayName: 'Deploy to Stage'
    variables:
      - group: mdwdo-dbx-release-stg
    jobs:
      - template: templates/jobs/deploy-azure-databricks-environment.yml
        parameters:
          environmentName: 'STG'
          serviceConnection: 'mdwdo-dbx-serviceconnection-stg'
          azureSubscriptionID: $(AZURE_SUBSCRIPTION_ID)

  - stage: deploy_to_prod
    displayName: 'Deploy to Production'
    variables:
      - group: mdwdo-dbx-release-prod
    jobs:
      - template: templates/jobs/deploy-azure-databricks-environment.yml
        parameters:
          environmentName: 'PROD'
          serviceConnection: 'mdwdo-dbx-serviceconnection-prod'
          azureSubscriptionID: $(AZURE_SUBSCRIPTION_ID)