# Starter Nutter pipeline

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  clusterID: 0516-144506-pug503
  databricks_host: https://adb-1503291521252601.1.azuredatabricks.net
  databricks_token: dapi3f1703a2a30dd59a487c0be9d67c3814
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    pip install nutter
  displayName: 'Install Nutter'

- script: |
    nutter run /Users/ganwa@microsoft.com/test_mynotebook $CLUSTER --recursive --junit_report
  displayName: 'Execute Nutter'
  env:
      CLUSTER: $(clusterID)
      DATABRICKS_HOST: $(databricks_host)
      DATABRICKS_TOKEN: $(databricks_token)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish Nutter results'
  condition: succeededOrFailed()
