import os

from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_MODEL_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_MODEL_DEPLOYMENT_NAME")
DOCUMENT_INTELLIGENCE_ENDPOINT = os.getenv("DOCUMENT_INTELLIGENCE_ENDPOINT")
AZURE_STORAGE_ACCOUNT_URL = os.getenv("AZURE_STORAGE_ACCOUNT_URL")
DOCUMENT_INTELLIGENCE_KEY = os.getenv("DOCUMENT_INTELLIGENCE_KEY")
CITATION_DB_ENABLED = os.getenv("CITATION_DB_ENABLED", "False").lower() == "true"
CITATION_DB_CONNECTION_STRING = os.getenv("CITATION_DB_CONNECTION_STRING")
OVERRIDE_DI_RESULTS = os.getenv("CITATION_DB_ENABLED", "False").lower() == "true"
LOG_LEVEL = os.getenv("EXPERIMENT_LOG_LEVEL", "INFO")
