from common.env_utils import EnvVar, EnvVarBool
from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_API_VERSION = EnvVar[str]("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_API_KEY = EnvVar[str]("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = EnvVar[str]("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_MODEL_DEPLOYMENT_NAME = EnvVar[str]("AZURE_OPENAI_MODEL_DEPLOYMENT_NAME")

DI_ENDPOINT = EnvVar[str]("DOCUMENT_INTELLIGENCE_ENDPOINT")
DI_KEY = EnvVar[str]("DOCUMENT_INTELLIGENCE_KEY")
DI_OVERRIDE_RESULTS = EnvVarBool("OVERRIDE_DI_RESULTS").value

AZURE_STORAGE_ACCOUNT_URL = EnvVar[str]("AZURE_STORAGE_ACCOUNT_URL")

CITATION_DB_ENABLED = EnvVarBool("CITATION_DB_ENABLED").value
CITATION_DB_CONNECTION_STRING = EnvVar[str]("CITATION_DB_CONNECTION_STRING")

LOG_LEVEL = EnvVar[str]("EXPERIMENT_LOG_LEVEL").value
