#!/bin/bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|hotfix)\/ADA-[0-9]+-[a-zA-Z0-9._ ]+$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

# regex to validate in commit msg
commit_regex='(ADA-[0-9]+|merge)'
error_msg="[POLICY] Aborting commit. Your commit message is missing either a JIRA Issue ('ADA-123') or 'Merge'"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
