trigger:
- master

variables:
  SLN_DIR: 'single_tech_samples\azuresql\ddo_samples_azuresql'
  SLN_NAME: 'ddo_samples_azuresql'
  SLN: '$(SLN_DIR)\$(SLN_NAME).sln'
  BUILD_PLATFORM: 'any cpu'
  BUILD_CONFIGURATION: 'release'

stages:
- stage: 'Build'
  displayName: 'Build'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: 'build_sql_dacpac'
    displayName: 'Build SQL DACPAC'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget'
    - task: NuGetCommand@2
      displayName: 'Restore Nuget packages'
      inputs:
        restoreSolution: '$(SLN)'
    - task: VSBuild@1
      displayName: 'Build solution sln'
      inputs:
        solution: '$(SLN)'
        platform: '$(BUILD_PLATFORM)'
        configuration: '$(BUILD_CONFIGURATION)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(SLN_DIR)\**\bin\$(BUILD_CONFIGURATION)\**.dacpac'
        artifact: 'sql_dacpac'
        publishLocation: 'pipeline'

- stage: 'Deploy'
  displayName: 'Deploy'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: 'deploy_sql_dacpac'
    displayName: 'Deploy SQL DACPAC'
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: 'sql_dacpac'
