name: "ADB Asset Bundle CI Linting"

on:
  pull_request:
    branches:
    - main
    paths:
    - "single_tech_samples/databricks/databricks_terraform/**"

env:
  UV_VERSION: ">=0.4.26"
  PYTHON_VERSION: "3.11"

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        version: ${{ env.UV_VERSION }}
        cache-dependency-glob: "**/requirements**.txt"

    - name: Install Python and Dependencies
      run: |
        uv python install ${{ env.PYTHON_VERSION }}
        uv tool install ruff

    - name: Run Ruff Lint
      run: |
        uv run ruff check single_tech_samples/databricks/databricks_terraform
