#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  pyspark:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports: 
    - 5004:5004
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # # This lets you avoid setting up Git again in the container
      # - ~/.gitconfig:/root/.gitconfig
      # - ~/.ssh:/root/.ssh:ro # does not work on Windows! Will need to generate in container :(
    
    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity
    env_file:
    - ../.env
