parameters:
- name: configFile
  type: string
- name: databricksJobName
  type: string
- name: databricksClusterId
  type: string
- name: databricksArtifactsPath
  type: string
- name: databricksDeploymentFilePath
  type: string

steps:
- script: echo "create ${{ parameters.databricksDeploymentFilePath }}"
- script: |
    cp ${{ parameters.configFile }} ${{ parameters.databricksDeploymentFilePath }}
    sed -i 's!<JOB_NAME>!${{ parameters.databricksJobName }}!' ${{ parameters.databricksDeploymentFilePath }}
    sed -i 's!<CLUSTER_ID>!${{ parameters.databricksClusterId }}!' ${{ parameters.databricksDeploymentFilePath }}
    sed -i 's!<FILE_PATH>!${{ parameters.databricksArtifactsPath }}!' ${{ parameters.databricksDeploymentFilePath }}
- script: cat ${{ parameters.databricksDeploymentFilePath }}
