-- Databricks notebook source
DROP TABLE IF EXISTS  POPULATION_COUNT;
CREATE TABLE IF NOT EXISTS POPULATION_COUNT AS (
  SELECT COUNT(*) AS TOTAL FROM US_POPULATION)

-- COMMAND ----------

DROP TABLE IF EXISTS  FIRST_YEAR;
CREATE TABLE IF NOT EXISTS FIRST_YEAR AS (
  SELECT date as YEAR, value as PUPULATION FROM US_POPULATION where date = (select MIN(date) from US_POPULATION))

-- COMMAND ----------
