parameters:
- name: environmentName
  type: string
- name: serviceConnection
  type: string

jobs:
- deployment: deploy_adf
  dependsOn: deploy_databricks
  displayName: 'Deploy to Azure Data Factory'
  pool:
    vmImage: 'windows-2019'
  variables:
    packageWheelName: $[ dependencies.deploy_databricks.outputs['deploy_databricks.setPackageWheelName.packageWheelName'] ]
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: mdwdataops_adfpublish
          path: 'adf_publish' 

        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
        - task: AzurePowerShell@4
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            ScriptPath: '$(Pipeline.Workspace)/ciartifacts/adf_scripts/deploymentadf.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\$(devAdfName)\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $true'
            azurePowerShellVersion: LatestVersion
          displayName: 'Azure PowerShell script: Stop ADF triggers'

        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on $(rgName)'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: '$(rgName)'
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateParametersForFactory.json'
            overrideParameters: -factoryName "$(adfName)" -P_Ingest_MelbParkingData_properties_0_typeProperties_notebookPath "$(databricksNotebookPath)/02_standardize" -P_Ingest_MelbParkingData_properties_0_typeProperties_0_egg "$(databricksDbfsLibPath)/$(packageWheelName)" -P_Ingest_MelbParkingData_properties_4_typeProperties_0_egg "$(databricksDbfsLibPath)/$(packageWheelName)" -Ls_AdlsGen2_01_properties_typeProperties_url "https://$(datalakeAccountName).dfs.core.windows.net/" -Ls_KeyVault_01_properties_typeProperties_baseUrl "$(kvUrl)" -Ls_Rest_MelParkSensors_01_properties_typeProperties_url "$(apiBaseUrl)" -P_Ingest_MelbParkingData_properties_4_typeProperties_notebookPath "$(databricksNotebookPath)/03_transform" -Ls_AzureDatabricks_01_properties_typeProperties_domain "$(databricksDomain)" -Ls_AzureDatabricks_01_properties_typeProperties_workspaceResourceId "$(databricksWorkspaceResourceId)"


        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Start ADF triggers'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            ScriptPath: '$(Pipeline.Workspace)/ciartifacts/adf_scripts/deploymentadf.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\$(devAdfName)\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $false'
            azurePowerShellVersion: LatestVersion