# This is the main pipeline for platform infrastructure, and deploys:
#
#   * The base infrastructure
#   * The Data Lake log sender function
#   * Azure Logic App for sending email notifications from Data Factory
#
# Note: After provisioning the base infrastructure, the recommended next step is to run the malware detection setup
# pipeline (defined by the create-malware-detection-setup.yml file).
#
---
trigger:
  - none

stages:
  - stage: Development
    variables:
      - template: ./variables/dev-environment.yml
    jobs:
      - template: ./jobs/create-infrastructure-job.yml
        parameters:
          environment: Development
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          locationFormatted: ${{ variables.locationFormatted }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          applicationInsightsName: ${{ variables.applicationInsightsName }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          virtualNetworkName: ${{ variables.virtualNetworkName }}
          keyVaultName: ${{ variables.keyVaultName }}
          coreInfrastructureSubnetName: ${{ variables.coreInfrastructureSubnetName }}
          publicCatalogSubnetName: ${{ variables.publicCatalogSubnetName }}
          subnetNumber: ${{ variables.subnetNumber }}
          subnetNames: ${{ variables.subnetNames }}
          subnetPrefixes: ${{ variables.subnetPrefixes }}
          purviewAccountName: ${{ variables.purviewAccountName }}
          dataLakeStorageAccountName: ${{ variables.dataLakeStorageAccountName }}
          dataFactoryName: ${{ variables.dataFactoryName }}
          storageContainerName: ${{ variables.storageContainerName }}
          dropzoneStorageContainerName: ${{ variables.dropzoneStorageContainerName }}
          publicIpAddressName: ${{ variables.publicIpAddressName }}
          purviewAdmins: ${{ variables.purviewAdmins }}
          databricksWorkspaceName: ${{ variables.databricksWorkspaceName }}
      - template: ./jobs/create-data-lake-log-sender-job.yml
        parameters:
          dependsOn:
            - BaseInfrastructure
          environment: Development
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          azureServiceConnection: ${{ variables.azureResourceManagerConnection }}
          logSenderFunctionAppName: ${{ variables.logSenderFunctionAppName }}
          dataLakeStorageAccountName: ${{ variables.dataLakeStorageAccountName }}
          targetLogAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          applicationInsightsName: ${{ variables.applicationInsightsName }}
      - template: ./jobs/create-email-sender-job.yml
        parameters:
          dependsOn:
            - BaseInfrastructure
          environment: Development
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          emailSenderLogicAppName: ${{ variables.emailSenderLogicAppName }}
          emailSenderRecipientAddress: ${{ variables.emailSenderRecipientAddress }}
          o365ConnectionName: ${{ variables.o365ConnectionName }}

  - stage: Test
    variables:
      - template: ./variables/test-environment.yml
    jobs:
      - template: ./jobs/create-infrastructure-job.yml
        parameters:
          environment: Test
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          locationFormatted: ${{ variables.locationFormatted }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          applicationInsightsName: ${{ variables.applicationInsightsName }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          virtualNetworkName: ${{ variables.virtualNetworkName }}
          keyVaultName: ${{ variables.keyVaultName }}
          coreInfrastructureSubnetName: ${{ variables.coreInfrastructureSubnetName }}
          publicCatalogSubnetName: ${{ variables.publicCatalogSubnetName }}
          subnetNumber: ${{ variables.subnetNumber }}
          subnetNames: ${{ variables.subnetNames }}
          subnetPrefixes: ${{ variables.subnetPrefixes }}
          purviewAccountName: ${{ variables.purviewAccountName }}
          dataLakeStorageAccountName: ${{ variables.dataLakeStorageAccountName }}
          dataFactoryName: ${{ variables.dataFactoryName }}
          storageContainerName: ${{ variables.storageContainerName }}
          dropzoneStorageContainerName: ${{ variables.dropzoneStorageContainerName }}
          publicIpAddressName: ${{ variables.publicIpAddressName }}
          purviewAdmins: ${{ variables.purviewAdmins }}
          databricksWorkspaceName: ${{ variables.databricksWorkspaceName }}
      - template: ./jobs/create-data-lake-log-sender-job.yml
        parameters:
          dependsOn:
            - BaseInfrastructure
          environment: Test
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          azureServiceConnection: ${{ variables.azureResourceManagerConnection }}
          logSenderFunctionAppName: ${{ variables.logSenderFunctionAppName }}
          dataLakeStorageAccountName: ${{ variables.dataLakeStorageAccountName }}
          targetLogAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          applicationInsightsName: ${{ variables.applicationInsightsName }}
      - template: ./jobs/create-email-sender-job.yml
        parameters:
          dependsOn:
            - BaseInfrastructure
          environment: Test
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          emailSenderLogicAppName: ${{ variables.emailSenderLogicAppName }}
          emailSenderRecipientAddress: ${{ variables.emailSenderRecipientAddress }}
          o365ConnectionName: ${{ variables.o365ConnectionName }}

  - stage: Production
    variables:
      - template: ./variables/prod-environment.yml
    jobs:
      - template: ./jobs/create-infrastructure-job.yml
        parameters:
          environment: Production
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          locationFormatted: ${{ variables.locationFormatted }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          applicationInsightsName: ${{ variables.applicationInsightsName }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          virtualNetworkName: ${{ variables.virtualNetworkName }}
          keyVaultName: ${{ variables.keyVaultName }}
          coreInfrastructureSubnetName: ${{ variables.coreInfrastructureSubnetName }}
          publicCatalogSubnetName: ${{ variables.publicCatalogSubnetName }}
          subnetNumber: ${{ variables.subnetNumber }}
          subnetNames: ${{ variables.subnetNames }}
          subnetPrefixes: ${{ variables.subnetPrefixes }}
          purviewAccountName: ${{ variables.purviewAccountName }}
          dataLakeStorageAccountName: ${{ variables.dataLakeStorageAccountName }}
          dataFactoryName: ${{ variables.dataFactoryName }}
          storageContainerName: ${{ variables.storageContainerName }}
          dropzoneStorageContainerName: ${{ variables.dropzoneStorageContainerName }}
          publicIpAddressName: ${{ variables.publicIpAddressName }}
          purviewAdmins: ${{ variables.purviewAdmins }}
          databricksWorkspaceName: ${{ variables.databricksWorkspaceName }}
      - template: ./jobs/create-data-lake-log-sender-job.yml
        parameters:
          dependsOn:
            - BaseInfrastructure
          environment: Production
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          azureServiceConnection: ${{ variables.azureResourceManagerConnection }}
          logSenderFunctionAppName: ${{ variables.logSenderFunctionAppName }}
          dataLakeStorageAccountName: ${{ variables.dataLakeStorageAccountName }}
          targetLogAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          applicationInsightsName: ${{ variables.applicationInsightsName }}
      - template: ./jobs/create-email-sender-job.yml
        parameters:
          dependsOn:
            - BaseInfrastructure
          environment: Production
          resourceGroup: ${{ variables.resourceGroup }}
          location: ${{ variables.location }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          emailSenderLogicAppName: ${{ variables.emailSenderLogicAppName }}
          emailSenderRecipientAddress: ${{ variables.emailSenderRecipientAddress }}
          o365ConnectionName: ${{ variables.o365ConnectionName }}
