trigger:
- main

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  SLN_NAME: 'ddo_samples_azuresql'
  SLN_DIR: 'single_tech_samples\azuresql\src\$(SLN_NAME)'
  SLN: '$(SLN_DIR)\$(SLN_NAME).sln'
  BUILD_PLATFORM: 'any cpu'
  BUILD_CONFIGURATION: 'release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget'

- task: NuGetCommand@2
  displayName: 'Restore Nuget packages'
  inputs:
    restoreSolution: '$(SLN)'

- task: VSBuild@1
  displayName: 'Build solution sln'
  inputs:
    solution: '$(SLN)'
    platform: '$(BUILD_PLATFORM)'
    configuration: '$(BUILD_CONFIGURATION)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.DefaultWorkingDirectory)'
    Contents: '$(SLN_DIR)\**\bin\$(BUILD_CONFIGURATION)\**'
    TargetFolder: '$(build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'sql_dacpac'