# This job will create and configure an Azure Logic App for sending notification emails based on events in
# Data Factory.
#
---
parameters:
  - name: environment
    type: string
  - name: resourceGroup
    type: string
  - name: location
    type: string
  - name: azureResourceManagerConnection
    type: string
  - name: logAnalyticsWorkspaceName
    type: string
  - name: emailSenderLogicAppName
    type: string
  - name: emailSenderRecipientAddress
    type: string
  - name: o365ConnectionName
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - deployment: EmailSenderLogicApp
    environment: ${{ parameters.environment }}
    dependsOn:
      - ${{ each depends in parameters.dependsOn }}:
          - ${{ depends }}
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: PowerShell@2
              inputs:
                filePath: "./scripts/agent/Set-AgentTools.ps1"
                pwsh: true
              displayName: Setup Agent Tools

            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{ parameters.azureResourceManagerConnection }}
                scriptType: "pscore"
                scriptLocation: "scriptPath"
                ScriptPath: "./scripts/environment/New-EnvironmentVariables.ps1"
                addSpnToEnvironment: true
              displayName: Set Azure Subscription ID to task variables

            - template: ../templates/O365_connector.yml
              parameters:
                subscriptionId: $(subscriptionId)
                azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                displayName: ${{ parameters.emailSenderRecipientAddress }}
                connectionName: ${{ parameters.o365ConnectionName }}

            - template: ../templates/df-email-logic-app.yml
              parameters:
                subscriptionId: $(subscriptionId)
                azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                emailSenderLogicAppName: ${{ parameters.emailSenderLogicAppName }}
                emailSenderRecipientAddress: ${{ parameters.emailSenderRecipientAddress }}
                logAnalyticsWorkspaceName: ${{ parameters.logAnalyticsWorkspaceName }}
                diagnosticSettingName: setByPipeline
