parameters:
- name: environmentName
  type: string
- name: serviceConnection
  type: string

jobs:
- deployment: deploy_wheel_to_synapse
  displayName: Deploy Wheel Package to Synapse
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            # az upgrade and apt-get command both failed for updating to 2.29.0 
            # version on ubuntu at this point
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          name: az_upgrade
          displayName: 'upgrade az cli to latest version'

        - script: |
            packageWheelName=$(ls ${WHEEL_FILE_PATH} | grep '^ddo_transform.*.whl$' | head -n 1)
            echo "Package wheel name is: $packageWheelName"
            echo "##vso[task.setvariable variable=packageWheelName;isOutput=true]$packageWheelName"
          env:
            WHEEL_FILE_PATH: $(Pipeline.Workspace)/ciartifacts/dist
          name: setPackageWheelName
          displayName: 'Set packageWheelName variable'

        - task: AzureCLI@2
          displayName: Upload package to Synapse workspace
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az synapse workspace-package upload \
              --workspace-name $(synapseWorkspaceName) \
              --package $(Pipeline.Workspace)/ciartifacts/dist/$(setPackageWheelName.packageWheelName)
        
        - task: AzureCLI@2
          displayName: Remove old version and add package to spark pool
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              oldPackage=$(az synapse spark pool show \
              --name $(synapseSparkPoolName) \
              --workspace-name $(synapseWorkspaceName) \
              --resource-group $(rgName) \
              --query customLibraries[].name -o tsv | grep ddo_transform)

              az synapse spark pool update \
              --name $(synapseSparkPoolName) \
              --workspace-name $(synapseWorkspaceName) \
              --resource-group $(rgName) \
              --package-action Remove \
              --package $oldPackage

              az synapse spark pool update \
              --name $(synapseSparkPoolName) \
              --workspace-name $(synapseWorkspaceName) \
              --resource-group $(rgName) \
              --package-action Add \
              --package $(setPackageWheelName.packageWheelName) \
              --library-requirements $(Pipeline.Workspace)/ciartifacts/synapse_pool_requirements/requirements.txt

