trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: IaCStage
  displayName: 'IaC Stage'
  jobs:
  - template: iac-template.yml
    parameters:
      IaCRepo: self
      buildingEnvironment: staging
- stage: IaCPrime
  displayName: 'IaC Prime'
  jobs:
  - template: iac-template.yml
    parameters:
      IaCRepo: self
      buildingEnvironment: prime
