trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: IaCStage
  displayName: 'IaC plan Stage (no terraform apply)'
  jobs:
  - template: iac-template.yml
    parameters:
      buildValidation: true
      IaCRepo: self
      buildingEnvironment: staging
- stage: IaCPrime
  displayName: 'IaC plan Prime(no terraform apply)'
  jobs:
  - template: iac-template.yml
    parameters:
      buildValidation: true
      IaCRepo: self
      buildingEnvironment: prime
