# This job creates all the resources of the base infrastructure.
#
# The following resources will be created and configured:
#
#   * Azure Monitoring:
#     * Application Insights
#     * Log Analytics
#   * Virtual network and subnets
#   * Key Vault
#   * Container Registry
#   * Data Lake Storage (Gen2)
#   * Application Gateway
#
---
parameters:
  - name: environment
    type: string
  - name: resourceGroup
    type: string
  - name: location
    type: string
  - name: locationFormatted
    type: string
  - name: azureResourceManagerConnection
    type: string
  - name: logAnalyticsWorkspaceName
    type: string
  - name: applicationInsightsName
    type: string
  - name: virtualNetworkName
    type: string
  - name: coreInfrastructureSubnetName
    type: string
  - name: publicCatalogSubnetName
    type: string
  - name: subnetNumber
    type: number
  - name: subnetNames
    type: string
  - name: subnetPrefixes
    type: string
  - name: keyVaultName
    type: string
  - name: purviewAccountName
    type: string
  - name: dataLakeStorageAccountName
    type: string
  - name: dataFactoryName
    type: string
  - name: storageContainerName
    type: string
  - name: dropzoneStorageContainerName
    type: string
  - name: publicIpAddressName
    type: string
  - name: purviewAdmins
    type: string
  - name: databricksWorkspaceName
    type: string

jobs:
  - deployment: BaseInfrastructure
    environment: ${{ parameters.environment }}
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: PowerShell@2
              inputs:
                filePath: "./scripts/agent/Set-AgentTools.ps1"
                pwsh: true
              displayName: Setup Agent Tools

            # This tasks provides the job with the following variables:
            #
            #   - subscriptionId
            #   - servicePrincipalObjectId
            #
            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{ parameters.azureResourceManagerConnection }}
                scriptType: "pscore"
                scriptLocation: "scriptPath"
                ScriptPath: "./scripts/environment/New-EnvironmentVariables.ps1"
                addSpnToEnvironment: true
              displayName: Set Azure Subscription ID to task variables

            - template: ../templates/log-analytics.yml
              parameters:
                subscriptionId: $(subscriptionId)
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                locationFormatted: ${{ parameters.locationFormatted }}
                logAnalyticsName: ${{ parameters.logAnalyticsWorkspaceName }}
                sku: pergb2018
                diagnosticSettingName: setByPipeline

            - template: ../templates/app-insights.yml
              parameters:
                subscriptionId: $(subscriptionId)
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                locationFormatted: ${{ parameters.locationFormatted }}
                appInsightsName: ${{ parameters.applicationInsightsName }}
                logAnalyticsName: ${{ parameters.logAnalyticsWorkspaceName }}

            - template: ../templates/vnet.yml
              parameters:
                subscriptionId: $(subscriptionId)
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                location: ${{ parameters.location }}
                locationFormatted: ${{ parameters.locationFormatted }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                virtualNetworkName: ${{ parameters.virtualNetworkName }}
                subnetNumber: ${{ parameters.subnetNumber }}
                subnetNames: ${{ parameters.subnetNames }}
                subnetPrefixes: ${{ parameters.subnetPrefixes }}
                logAnalyticsName: ${{ parameters.logAnalyticsWorkspaceName }}
                diagnosticSettingName: setByPipeline

            - template: ../templates/key-vault.yml
              parameters:
                subscriptionId: $(subscriptionId)
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                locationFormatted: ${{ parameters.locationFormatted }}
                keyVaultName: ${{ parameters.keyVaultName }}
                logAnalyticsName: ${{ parameters.logAnalyticsWorkspaceName }}
                diagnosticSettingName: setByPipeline
                servicePrincipalObjectId: $(servicePrincipalObjectId)
                subnetName: ${{ parameters.coreInfrastructureSubnetName }}
                virtualNetworkName: ${{ parameters.virtualNetworkName }}

            - template: ../templates/purview.yml
              parameters:
                subscriptionId: $(subscriptionId)
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                purviewAccountName: ${{ parameters.purviewAccountName }}
                purviewAdmins: ${{ parameters.purviewAdmins }}

            - template: ../templates/data-lake.yml
              parameters:
                subscriptionId: $(subscriptionId)
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                storageAccountName: ${{ parameters.dataLakeStorageAccountName }}
                storageContainerName: ${{ parameters.storageContainerName }}
                dropzoneStorageContainerName: ${{ parameters.dropzoneStorageContainerName }}
                location: ${{ parameters.location }}
                keyVaultName: ${{ parameters.keyVaultName }}
                purviewAccountName: ${{ parameters.purviewAccountName }}
                subnetName: ${{ parameters.coreInfrastructureSubnetName }}
                virtualNetworkName: ${{ parameters.virtualNetworkName }}

            - template: ../templates/databricks.yml
              parameters:
                subscriptionId: $(subscriptionId)
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                workspaceName: ${{ parameters.databricksWorkspaceName }}
                storageAccountName: ${{ parameters.dataLakeStorageAccountName }}
                storageContainerName: ${{ parameters.dropzoneStorageContainerName }}
                keyVaultName: ${{ parameters.keyVaultName }}
                databricksSecretName: "databricks-pat"
                
            - template: ../templates/data-factory.yml
              parameters:
                subscriptionId: $(subscriptionId)
                dataFactoryName: ${{ parameters.dataFactoryName }}
                resourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
                resourceGroupName: ${{ parameters.resourceGroup }}
                location: ${{ parameters.location }}
                keyVaultName: ${{ parameters.keyVaultName }}
                diagnosticSettingName: setByPipeline
                logAnalyticsName: ${{ parameters.logAnalyticsWorkspaceName }}
                purviewAccountName: ${{ parameters.purviewAccountName }}
                storageAccountName: ${{ parameters.dataLakeStorageAccountName }}
                databricksSecretName: "databricks-pat"
                databricksWorkspaceUrl: $(databricksWorkspaceUrl)
                databricksClusterId: $(databricksClusterId)
