trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_USERNAME: $(AZURE_USERNAME)
  AZURE_PASSWORD: $(AZURE_PASSWORD)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

steps:
  - task: AzureCLI@2
    inputs:
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo $(AZURE_PASSWORD) | az login -u $(AZURE_USERNAME) --password $(AZURE_PASSWORD) --output none
        az account set --subscription $(ARM_SUBSCRIPTION_ID)

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: Terraform@0
    inputs:
      command: 'init'
      workingDirectory: '<path to your Terraform configuration>'

  - task: Terraform@0
    inputs:
      command: 'plan'
      workingDirectory: '<path to your Terraform configuration>'
      additionalArgs: '-out=tfplan'

  - task: Terraform@0
    inputs:
      command: 'apply'
      workingDirectory: '<path to your Terraform configuration>'
      additionalArgs: '-auto-approve "tfplan"'
