name: Broken Hyperlinks Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  check-links:
    name: linkspector
    runs-on: ubuntu-22.04 # https://github.com/w3c/webref/pull/1431/commits/1be8e31fe7777287bd5fd48217c9dcea269196b9
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          config_file: '.linkspector.yml'
